"""
Django settings for pbcuk project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! Override via env SECRET_KEY
SECRET_KEY = os.getenv('SECRET_KEY', 'insecure-dev-key')

# SECURITY WARNING: don't run with debug turned on in production! DEBUG=0/1
DEBUG = os.getenv('DEBUG', '0') in ['1', 'true', 'True']

# Comma-separated hostnames/IPs in ALLOWED_HOSTS env var
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'quotes',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pbcuk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pbcuk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL and (DATABASE_URL.startswith('postgres://') or DATABASE_URL.startswith('postgresql://')):
    # Minimal URL parsing without extra dependency
    # Format: postgres://user:pass@host:port/dbname
    try:
        url_body = DATABASE_URL.split('://', 1)[1]
        creds_host, db_name = url_body.rsplit('/', 1)
        creds, host_port = creds_host.split('@')
        user, password = creds.split(':', 1)
        host, port = host_port.split(':', 1)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': db_name,
                'USER': user,
                'PASSWORD': password,
                'HOST': host,
                'PORT': port,
            }
        }
    except Exception:
        # Fallback to sqlite on parse failure
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
elif os.getenv('POSTGRES_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'django'),
            'USER': os.getenv('POSTGRES_USER', 'django'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'django'),
            'HOST': os.getenv('POSTGRES_HOST'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'static_root'
if not DEBUG:
    # Use compressed manifest storage in production for cache-busting
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Shared secret for external payment/webhook integration (override via env in production)
PAYMENT_WEBHOOK_SECRET = os.getenv('DJANGO_PAYMENT_WEBHOOK_SECRET', 'change-me')  # override in production

# Reverse proxy / SSL settings for Caddy / proxies
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF trusted origins (comma-separated list in env)
_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',') if o.strip()]

# Stripe keys
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'pk_test_51STqMaKfAosSgUj4h0v4OtniHdOltnIkohoWxIwcHIB2I9Wl80GEiPLnsBnqpIm3NNUStNsuDGc6g9d4vbbdbKk100FlEcl6PI')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_51STqMaKfAosSgUj4wK7taLAL7FIO8fTVNn8qk7spV932dYfscPn1vEOrsODXvCjSfb5QA5Q3huGxfsFgH3DkHy1A00hOqi9Pn1')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_3994f4337bf88d0332d78fe3c2b29ce8a9234c088d320b742f62697b06dab29f')

# Stripe fee config (strings; parsed where used)
# If STRIPE_FEE_GROSS_UP=true, card charge is increased so that net after fees ≈ invoice amount
STRIPE_FEE_PERCENT = os.getenv('STRIPE_FEE_PERCENT', '2.9')
STRIPE_FEE_FIXED = os.getenv('STRIPE_FEE_FIXED', '0.20')
STRIPE_FEE_GROSS_UP = os.getenv('STRIPE_FEE_GROSS_UP', 'true') in ['1', 'true', 'True']

# Bank transfer details (used on Payment Methods page); values may be overridden by CompanyDetails model if present
COMPANY_BANK_NAME = os.getenv('COMPANY_BANK_NAME', 'Revolut Ltd')
COMPANY_BANK_ACCOUNT_NAME = os.getenv('COMPANY_BANK_ACCOUNT_NAME', 'Jack Oldfield')
COMPANY_BANK_ACCOUNT_NUMBER = os.getenv('COMPANY_BANK_ACCOUNT_NUMBER', '75092409')
COMPANY_BANK_SORT_CODE = os.getenv('COMPANY_BANK_SORT_CODE', '042909')
COMPANY_BANK_IBAN = os.getenv('COMPANY_BANK_IBAN', 'GB02 REVO 0099 7070 6708 45')
COMPANY_BANK_BIC = os.getenv('COMPANY_BANK_BIC', 'REVOGB21')

# Jazzmin basic branding
JAZZMIN_SETTINGS = {
    "site_title": "PBC UK Admin",
    "site_header": "PBC UK Admin",
    "site_brand": "PBC UK",
    "welcome_sign": "Welcome to PBC UK Admin",
    "show_ui_builder": False,
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-navy",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-navy",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "spacelab",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}

# Email backend (console for development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'support@prebuiltcomputers.uk'
