# Generated by Django 5.2.8 on 2025-11-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
