# Generated by Django 5.2.8 on 2025-11-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='not_vat_registered',
            field=models.BooleanField(default=True),
        ),
    ]
