# Generated by Django 5.2.8 on 2025-11-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_not_vat_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='reservation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
