# Generated by Django 5.2.8 on 2025-11-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_reservation_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='reservation_session_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
