# Generated by Django 5.2.8 on 2025-11-13 23:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_reservation_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=8),
        ),
    ]
