# Generated by Django 5.2.8 on 2025-11-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_invoice_paid_at_invoicepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteacceptance',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
